FROM public.ecr.aws/sagemaker/sagemaker-distribution:latest-cpu
COPY vscode-reh-web-linux-x64/ /opt/conda/share/sagemaker-code-editor/
# Only enable this line for testing custom extensions marketplace feature
# ENV EXTENSIONS_GALLERY='{"serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery", "itemUrl": "https://marketplace.visualstudio.com/items"}'
ENTRYPOINT ["entrypoint-code-editor"]